language: rust
rust: nightly
sudo: true
env:
  global:
    - RUST_TEST_THREADS: 1
before_script:
  - cd ..
  - wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - wget -q http://iweb.dl.sourceforge.net/project/sdl2gfx/SDL2_gfx-1.0.0.tar.gz
  - tar xf SDL2-*.tar.gz
  - tar xf SDL2_gfx-*.tar.gz
  - cd SDL2-*
  - ./configure && make && sudo make install
  - cd -
  - cd SDL2_gfx-*
  - ./configure && make && sudo make install
  - cd -
  - cd rust-sdl2_gfx
  - rustc --version
script:
  - cargo build -v
  - cargo test -- --nocapture
  - cargo bench -v
after_script:
  - cargo run --example percolation 20 1000
