language: rust
rust: nightly
sudo: true
env:
  global:
    - RUST_TEST_THREADS: 1
before_script:
  - rustc --version
script:
  - cargo build -v
  - cargo test -- --nocapture
  - cargo bench -v
after_script:
  - cargo run --example percolation 20 1000
